<?php

namespace App\Enums;

enum LicenseLogEvent: string
{
    case LICENSE_CREATED = 'LICENSE_CREATED';
    case ACTIVATION_ATTEMPT = 'ACTIVATION_ATTEMPT';
    case ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
    case ACTIVATION_FAILED = 'ACTIVATION_FAILED';
    case TOKEN_ISSUED = 'TOKEN_ISSUED';
    case TOKEN_REFRESHED = 'TOKEN_REFRESHED';
    case BINDING_RESET = 'BINDING_RESET';
    case TOKEN_INVALIDATED = 'TOKEN_INVALIDATED';
    case LICENSE_SUSPENDED = 'LICENSE_SUSPENDED';
    case LICENSE_UNSUSPENDED = 'LICENSE_UNSUSPENDED';
    case LICENSE_REVOKED = 'LICENSE_REVOKED';
    case LICENSE_RENEWED = 'LICENSE_RENEWED';
    case LICENSE_EXPIRED = 'LICENSE_EXPIRED';
    case VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
    case VERIFICATION_FAILED = 'VERIFICATION_FAILED';
    case API_KEY_CREATED = 'API_KEY_CREATED';
    case API_KEY_REVOKED = 'API_KEY_REVOKED';
    case APPLICATION_CREATED = 'APPLICATION_CREATED';
    case APPLICATION_UPDATED = 'APPLICATION_UPDATED';
    case APPLICATION_TOGGLED = 'APPLICATION_TOGGLED';
}
